name: Publish docker image
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and publish docker image
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build and publish
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: whoan
        password: "${{ secrets.GITHUB_TOKEN }}"
        registry: docker.pkg.github.com
        image_name: cohortextractor
        push_git_tag: true
